services:
  webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
        - ./code:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - ${NGINX_PORT:-80}:80
      depends_on:
        - php-fpm
      restart: unless-stopped

  php-fpm:
    image: php:8.2-fpm
    working_dir: /application
    volumes:
      - ./code:/application
    restart: unless-stopped

  composer:
    image: composer:latest
    volumes:
      - ./code:/app