
@baseUrl = http://127.0.0.1:8080

## ROOT

### site root
GET {{baseUrl}}/ HTTP/1.1

### wrong url
GET {{baseUrl}}/blog/pdf/1 HTTP/1.1



##BLOG POSTS

### Blog root
GET {{baseUrl}}/blog HTTP/1.1


### Blog page
GET {{baseUrl}}/blog/page/1 HTTP/1.1

### Get plog post by id
GET {{baseUrl}}/blog/1 HTTP/1.1

### Create new blog post
POST {{baseUrl}}/blog HTTP/1.1
Content-Type: : application/json

{
    "author": "author_{{$timestamp}}",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi congue varius urna eu lacinia. Aenean eleifend porttitor mi at dictum. Pellentesque ut eleifend dolor. Cras condimentum quam vitae felis placerat pulvinar. Vivamus mattis ultrices diam. Aliquam suscipit, elit ac facilisis efficitur, nisl mi convallis libero, quis sagittis sapien nibh finibus ante. Quisque hendrerit vestibulum ante, non pulvinar libero cursus ac. Praesent lacinia lobortis nunc, eget ultricies turpis bibendum sit amet. Sed tempor, arcu consectetur sagittis varius, neque felis efficitur ligula, sed tempor ante magna id tortor. Donec sit amet dui leo. Duis commodo leo at tortor scelerisque, et laoreet arcu blandit. Vivamus ac odio lorem. Nullam bibendum elit eu quam rhoncus efficitur. Sed felis leo, feugiat vel sem eget, condimentum pretium ex. Phasellus ut arcu et lacus elementum sagittis. Vestibulum fermentum luctus risus ut eleifend. "
}

### Try Create new blog post with wrong fields
POST {{baseUrl}}/blog HTTP/1.1
Content-Type: : application/json

{
    "author_error": "author_{{$timestamp}}",
    "text_error": "Lorem ipsum"
}



### Update blog post
PUT {{baseUrl}}/blog/2 HTTP/1.1
Content-Type: : application/json

{
    "author": "3erwer3",
    "text": "sdfsdf"
}

### delete blog post
DELETE {{baseUrl}}/blog/5 HTTP/1.1
Content-Type: : application/json


##COMMENTS

### Get comments of blog post
GET {{baseUrl}}/blog/1/comments HTTP/1.1

### Create new comment for blog post
POST {{baseUrl}}/comment/1 HTTP/1.1
Content-Type: : application/json

{
    "author": "author_{{$timestamp}}",
    "text": "Lorem ipsum dolor sit amet."
}


### Create new comment with wrong fields
POST {{baseUrl}}/comment/1 HTTP/1.1
Content-Type: : application/json

{
    "author_error": "author_{{$timestamp}}",
    "text_error": "Lore"
}

